### ISSUE TITLE
Quote keys containing special characters

### ISSUE THREAD

**Issue by ellis** [AndrewRedican/react-json-editor-ajrm#21]
1. What version of RJEA are you using (react-json-editor-ajrm version)?

v2.4.4

2. What operating system and processor architecture are you using?

Mac OS

3. What did you do?

Tried to edit a JSON object whose keys have "special characters".

4. What did you expect to see?

An properly editable object

5. What did you see instead?

![image](https://user-images.githubusercontent.com/97852/42418987-20721f8a-82ac-11e8-9786-2d1b323c7492.png)

In the above screenshot, when I changed the value of `state` to `paused`, the error shows up for line 4.  I can temporarily fix the error by manually putting the key in quotes (i.e. `'10018-00'`), but then the next key that starts with a number or contains other special characters gets marked as an error.

Could you please provide a fix to this?  One possible fix would be to always quote keys that will cause parsing errors if left unquoted; or to just always quote keys.

Cheers!

**Comment by AndrewRedican** [comment]
Hey @ellis,

Just to confirm, are you passing this to the component through `placeholder` property or is it manual user input?

I think there are two issue here:

First I am not sure if keys begining with a number are considered as possible keys in the logic of component, ergo  _"number can only follow '[', ':', ',' tokens"_. I will update the component's logic to make sure it does consider it as an actual key.

For the second issue, where special characters are used in keys. The following is not valid syntax, and should return an error. 
```
{ 100-18 : 3 }
```
If you are manually pasting this into the component, the expected behavoir should be to return an error.
I wanted to confirm you were passing this data through the `placeholder` property, in which case, you are right, the component should render this key wrapped around quotes.

**Comment by ellis** [comment]
Hi @AndrewRedican - I'm passing a json object through the placeholder property, so the json looks like:

```json
{
  "state": "paused",
  "groups": {
    "10018-00": {
      "aliases": ["10018-00"],
      "state": "enabled"
    }
  }
}
```

My thought was simply that if the key "10018-00" would get automatically quoted, that would solve the problem, so that the results in the editor be valid.  But you may have a better solution in mind... :)

**Comment by AndrewRedican** [comment]
Hey @ellis,

The first portion of this issue has been fixed. Object keys can now be numbers and can also be "reservered" words, such as `null`, `false`, `true`, and `undefined` are all valid key names. This is available in the latest RJEA version `v2.4.6`.

In regards to keys such as `10018-00` passed to RJEA component through its placeholder property, will render these keys wrapped within quotes `'10018-00'` automatically. This update should be comming up shortly.

**Comment by PatrickSachs** [comment]
Since this is probably the same issue, quotes in keys also need to be escaped:
```json
{
  "oh i don't have any channels": {
    "desc": "That kinda explains why the channels list was empty... Mhm...",
    "lang": 0,
    "type": 0,
    "set": 0
  },
  "test standard channel": {
    "desc": "Testing channel support....",
    "lang": 0,
    "type": 0,
    "set": 1
  }
}
```

Creates the following output: (Syntax Error in the second line: `Missing closing ' quote on key at line 2`)
```js
{
  'oh i don't have any channels': {
    desc: 'That kinda explains why the channels list was empty... Mhm...',
    lang: 0,
    type: 0,
    set: 0
  },
  'test standard channel': {
    desc: '"Testing if quoted strings are really required.",Mhhh...',
    lang: 0,
    type: 0,
    set: 0
  }
}
```

**Comment by AndrewRedican** [comment]
Hey @PatrickSachs, I will also address this in the next update. Thanks for your input.

**Comment by AndrewRedican** [comment]
Hey @ellis, special key names that require to be wrapped in quotes now do.
Hey @PatrickSachs, quotes in keys are now escaped.

This fixes are available in the latest version of `react-json-editor-ajrm@2.4.7`

**Comment by PatrickSachs** [comment]
Thanks for the fix! Unfortunately I'm still getting an error with double quotes in values:
![screenshot_2](https://user-images.githubusercontent.com/7840502/42733939-432b5110-883b-11e8-808c-1b497c6fc86d.png)
If I escape the double quotes everything seems to work fine:
![screenshot_3](https://user-images.githubusercontent.com/7840502/42733949-50a12bda-883b-11e8-907b-c7e2238e88b3.png)
This is the full data set in case you need it for reproduction:
```json
{
  "general": {
    "address": "localhost",
    "port": 8431,
    "alarmrefreshcount": 3,
    "alarmrefreshinterval": 10,
    "watchdesktopstate": false,
    "alarmenabled": true
  },
  "channels": {
    "test standard channel": {
      "desc": "\"Testing if quoted strings are really required.\",Mhhh...",
      "lang": 0,
      "type": 0,
      "set": 0
    },
    "oh i don't have any channels": {
      "desc": "That kinda explains why the channels list was empty... Mhm...",
      "lang": 0,
      "type": 0,
      "set": 0
    }
  },
  "alarm_1": {
    "@@sendalarmtoall@@": false,
    "@@alarm@@": 0,
    "@@infogroup@@": "Infogroup Yo",
    "@@statustime@@": 5,
    "@@statuscaption@@": "The alarm has been sent!",
    "@alarmsettingname": "Basic Alarm",
    "allclear": {
      "popup": false,
      "cancloseonusersdesktop": true,
      "cancloseonwinlogondesktop": true,
      "soundfile": "",
      "loudness": false
    },
    "templatename": "Basic Alarm",
    "time": 1000,
    "keys": [
      "VK_CONTROL",
      "VK_F6"
    ]
  },
  "alarm_2": {
    "@@sendalarmtoall@@": false,
    "@@alarm@@": 1,
    "@@infogroup@@": "Infogroup Yo",
    "@@statustime@@": 5,
    "@@statuscaption@@": "The alarm has been sent!",
    "@alarmsettingname": "Extended Alarm",
    "allclear": {
      "popup": false,
      "cancloseonusersdesktop": true,
      "cancloseonwinlogondesktop": true,
      "soundfile": "",
      "loudness": false
    },
    "templatename": "Extended Alarm",
    "time": 1000,
    "keys": [
      "VK_CONTROL",
      "VK_F8"
    ]
  }
}
```

**Comment by AndrewRedican** [comment]
I'll look into this today.
